name: Build releases
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Build tags'
        required: true
        type: string
        
jobs:
  build-linux-android: 
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      # - run: |
      #     sudo apt-get update -y
      #     sudo apt-get install -y ninja-build libgtk-3-dev
      # - run: flutter build linux
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          token:  ${{ secrets.GITHUB_TOKEN }}
          artifacts: 'build/app/outputs/apk/release/*.apk,'
  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Clone repository
  #       uses: actions/checkout@v4
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         channel: stable
  #     - run: flutter pub get
  #     - run: flutter build windows
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: Release ${{ github.ref }}
